# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (f74b5957-ac12-438a-98c9-101c970bfee5)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t weuacr25.azurecr.io/web-game:tag 2048-game
      az acr login -n weuacr25
      docker push weuacr25.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1 (f74b5957-ac12-438a-98c9-101c970bfee5)'
    azureResourceGroup: 'weu-rg'
    kubernetesCluster: 'weu-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1 (f74b5957-ac12-438a-98c9-101c970bfee5)'
    azureContainerRegistry: 'weuacr25.azurecr.io'
    forceUpdate: false
